# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ca_analyzer.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 52))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 52))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.widget_3)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 40))
        self.comboBox.setMaximumSize(QtCore.QSize(200, 40))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.toolButton = QtWidgets.QToolButton(self.widget_3)
        self.toolButton.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton.setStyleSheet("background-image: url(:/analyzer/images/prev_file.bmp);\n"
"background-repeat: no-repeat;")
        self.toolButton.setText("")
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_2.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_2.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_2.setStyleSheet("background-image: url(:/analyzer/images/next_file.bmp);")
        self.toolButton_2.setText("")
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_2.addWidget(self.toolButton_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 40))
        self.comboBox_2.setMaximumSize(QtCore.QSize(100, 40))
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.widget_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(100, 40))
        self.comboBox_3.setMaximumSize(QtCore.QSize(100, 40))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        self.toolButton_3 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_3.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_3.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_3.setStyleSheet("background-image: url(:/analyzer/images/raw_image.bmp);")
        self.toolButton_3.setText("")
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout_2.addWidget(self.toolButton_3)
        self.toolButton_4 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_4.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_4.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_4.setStyleSheet("background-image: url(:/analyzer/images/actual_size.bmp);")
        self.toolButton_4.setText("")
        self.toolButton_4.setObjectName("toolButton_4")
        self.horizontalLayout_2.addWidget(self.toolButton_4)
        self.toolButton_5 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_5.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_5.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_5.setStyleSheet("background-image: url(:/analyzer/images/play.bmp);")
        self.toolButton_5.setText("")
        self.toolButton_5.setObjectName("toolButton_5")
        self.horizontalLayout_2.addWidget(self.toolButton_5)
        self.toolButton_6 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_6.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_6.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_6.setStyleSheet("background-image: url(:/analyzer/images/option.bmp);")
        self.toolButton_6.setText("")
        self.toolButton_6.setObjectName("toolButton_6")
        self.horizontalLayout_2.addWidget(self.toolButton_6)
        self.toolButton_7 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_7.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_7.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_7.setStyleSheet("background-image: url(:/analyzer/images/crop.bmp);")
        self.toolButton_7.setText("")
        self.toolButton_7.setObjectName("toolButton_7")
        self.horizontalLayout_2.addWidget(self.toolButton_7)
        self.toolButton_8 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_8.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_8.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_8.setStyleSheet("background-image: url(:/analyzer/images/show_roi.bmp);")
        self.toolButton_8.setText("")
        self.toolButton_8.setObjectName("toolButton_8")
        self.horizontalLayout_2.addWidget(self.toolButton_8)
        self.toolButton_9 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_9.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_9.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_9.setStyleSheet("background-image: url(:/analyzer/images/show_label.bmp);")
        self.toolButton_9.setText("")
        self.toolButton_9.setObjectName("toolButton_9")
        self.horizontalLayout_2.addWidget(self.toolButton_9)
        self.toolButton_10 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_10.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_10.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_10.setStyleSheet("background-image: url(:/analyzer/images/delete.bmp);")
        self.toolButton_10.setText("")
        self.toolButton_10.setObjectName("toolButton_10")
        self.horizontalLayout_2.addWidget(self.toolButton_10)
        self.toolButton_11 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_11.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_11.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_11.setStyleSheet("background-image: url(:/analyzer/images/delete_all.bmp);")
        self.toolButton_11.setText("")
        self.toolButton_11.setObjectName("toolButton_11")
        self.horizontalLayout_2.addWidget(self.toolButton_11)
        self.toolButton_12 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_12.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_12.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_12.setStyleSheet("background-image: url(:/analyzer/images/display_roi.bmp);")
        self.toolButton_12.setText("")
        self.toolButton_12.setObjectName("toolButton_12")
        self.horizontalLayout_2.addWidget(self.toolButton_12)
        self.toolButton_13 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_13.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_13.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_13.setStyleSheet("background-image: url(:/analyzer/images/export_roi.bmp);")
        self.toolButton_13.setText("")
        self.toolButton_13.setObjectName("toolButton_13")
        self.horizontalLayout_2.addWidget(self.toolButton_13)
        self.toolButton_14 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_14.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_14.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_14.setStyleSheet("background-image: url(:/analyzer/images/extract_xt.bmp);")
        self.toolButton_14.setText("")
        self.toolButton_14.setObjectName("toolButton_14")
        self.horizontalLayout_2.addWidget(self.toolButton_14)
        self.toolButton_15 = QtWidgets.QToolButton(self.widget_3)
        self.toolButton_15.setMinimumSize(QtCore.QSize(40, 40))
        self.toolButton_15.setMaximumSize(QtCore.QSize(40, 40))
        self.toolButton_15.setStyleSheet("background-image: url(:/analyzer/images/info.bmp);")
        self.toolButton_15.setText("")
        self.toolButton_15.setObjectName("toolButton_15")
        self.horizontalLayout_2.addWidget(self.toolButton_15)
        self.horizontalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setContentsMargins(2, 0, 0, 0)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setMinimumSize(QtCore.QSize(200, 12))
        self.label.setMaximumSize(QtCore.QSize(200, 12))
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.widget_4)
        self.horizontalScrollBar.setMinimumSize(QtCore.QSize(200, 22))
        self.horizontalScrollBar.setMaximumSize(QtCore.QSize(200, 22))
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.verticalLayout_3.addWidget(self.horizontalScrollBar)
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.widget_2)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1260, 18))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")

        self.retranslateUi(MainWindow)
        self.comboBox_3.currentIndexChanged['int'].connect(MainWindow.change_channel_color)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Ca2+ sparks"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ca2+ blinks"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Ca2+ sparks/blinks"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Ca2+ translents"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Multi"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Red"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Green"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Blue"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "Yellow"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "Purple"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "Cyan"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "White"))
        self.toolButton_4.setToolTip(_translate("MainWindow", "<html><head/><body><p>Actual Size</p></body></html>"))
        self.toolButton_5.setToolTip(_translate("MainWindow", "<html><head/><body><p>Analyze</p></body></html>"))
        self.toolButton_6.setToolTip(_translate("MainWindow", "<html><head/><body><p>Set Configration</p></body></html>"))
        self.toolButton_7.setToolTip(_translate("MainWindow", "<html><head/><body><p>Crop Image</p></body></html>"))
        self.toolButton_8.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show Or Hide ROI</p></body></html>"))
        self.toolButton_9.setToolTip(_translate("MainWindow", "<html><head/><body><p>Show Or Hide ROI#</p></body></html>"))
        self.toolButton_10.setToolTip(_translate("MainWindow", "<html><head/><body><p>Delete Current ROI</p></body></html>"))
        self.toolButton_11.setToolTip(_translate("MainWindow", "<html><head/><body><p>Delete All ROIs</p></body></html>"))
        self.toolButton_12.setToolTip(_translate("MainWindow", "<html><head/><body><p>Plot ROI Traces</p></body></html>"))
        self.toolButton_13.setToolTip(_translate("MainWindow", "<html><head/><body><p>Export Results</p></body></html>"))
        self.toolButton_14.setToolTip(_translate("MainWindow", "<html><head/><body><p>Export Time Traces</p></body></html>"))
        self.toolButton_15.setToolTip(_translate("MainWindow", "<html><head/><body><p>File Information</p></body></html>"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
